### ISSUE TITLE
Login button in Console widget should have a callback

### ISSUE THREAD

**Issue by Hixie** [Hixie/cuddlyworld-ide#41]
I'd like to be able to do:
```
Console(
  onLogin: () { ... }
)
```
...so that I can have it automatically switch to the Console tab.

**Comment by treeplate** [comment]
Again, this is not strictly a catalog problem

**Comment by treeplate** [comment]
you mean SettingsTab(...)?

**Comment by treeplate** [comment]
there's no real idea of `onLogin` on Console
