### ISSUE TITLE
Classes dropdown should be organized

### ISSUE THREAD

**Issue by Hixie** [Hixie/cuddlyworld-ide#47]
e.g. TThing subclasses in a separate section than TLocation subclasses

**Comment by treeplate** [comment]
Preferred: organize `debug classes of TAtom` server-side

**Comment by Hixie** [comment]
that could work. Maybe something like
```
> debug classes of TAtom
Classes are:
 - TFoo
    - TBar
 - TBaz
    - TQuux
    - TFroboz
  ```

**Comment by Hixie** [comment]
i sorted the list to have things before locations, and sorted each part alphabetically.
