### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by treeplate** [Hixie/cuddlyworld-ide#60]
When on a hole (`debug teleport hole`) going down does:
![image](https://user-images.githubusercontent.com/51892395/97823789-d7f3ee00-1c6e-11eb-86a8-be26a2e2abf6.png)

**Comment by Hixie** [comment]
I haven't checked but I think it's because holes normally don't let anything be "on" them (things automatically fall "in" to holes), and "debug teleport" bypasses that.

**Comment by treeplate** [comment]
closing due to previous comment
