### ISSUE TITLE
TAirLocation cdNorth to TSign doesn't work

### ISSUE THREAD

**Issue by treeplate** [Hixie/cuddlyworld-ide#73]
Make a `TAirLocation` connected `loAutoDescribe loPermissibleNavigationTarget loVisibleFromFarAway cdNorth` to a `TSign`.
Add the AirLocation to the cart and add to world.
![image](https://user-images.githubusercontent.com/51892395/99885830-86df7600-2bec-11eb-9a5f-dca95b347f78.png)
Instead add both.
`drop sign`.
![image](https://user-images.githubusercontent.com/51892395/99885816-6b746b00-2bec-11eb-8505-72b0b5ba1861.png)

That's a problem.

**Comment by treeplate** [comment]
should this be a ide-side error message saying something like "You can only connect rooms to each other!"?

**Comment by treeplate** [comment]
> should this be a ide-side error message saying something like "You can only connect rooms to each other!"?

@Hixie

**Comment by Hixie** [comment]
check the assertion but yeah that seems reasonable

**Comment by treeplate** [comment]
duplicate of #80
