### ISSUE TITLE
make > be more visible

### ISSUE THREAD

**Issue by treeplate** [Hixie/cuddlyworld-ide#9]
This is the console prompt:
![image](https://user-images.githubusercontent.com/51892395/96386995-fd9fd400-1153-11eb-9794-17b1416ea0d4.png)
When it's not selected, however,
![image](https://user-images.githubusercontent.com/51892395/96387007-1c9e6600-1154-11eb-8742-bef19e8f38cb.png)
there's no `>`.

**Comment by Hixie** [comment]
yeah i noticed that. haven't looked into it yet.
